branch-protection: {}
deck:
  spyglass: {}
gerrit: {}
owners_dir_blacklist:
  default: null
  repos: null
plank: {}
push_gateway: {}
sinker: {}
tide:
  context_options:
    required-if-present-contexts: null
